import type { Metadata } from "next";
import "./globals.css";
import { LayoutSidebarProvider } from "@/providers/sidebar-provider";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/providers/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"

  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <LayoutSidebarProvider>
              <main className="p-8">
                {children}
              </main>
          </LayoutSidebarProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
