import type { Metadata } from "next";
import "./globals.css";
import { LayoutSidebarProvider as SidebarProvider } from "@/providers/sidebar-provider";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme-provider";
import { AuthProvider } from "@/providers/auth-provider";
import { I18nProvider } from "@/providers/i18n-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  const lang = cookieStore.get("i18next")?.value || "en";
  const defaultOpen = cookieStore.get("sidebar:state")?.value === "true";

  return (
    <html lang={lang} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AuthProvider>
            <I18nProvider locale={lang}>
              <SidebarProvider>
                <main className="p-8">
                {children}
                </main>
                <Toaster />
              </SidebarProvider>
            </I18nProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
